version: '3'

services:
  server:
    build: .
    env_file:
      - mongo.env
    ports:
      - 9000:9000
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - mongo.env
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js